services:
  - type: worker
    name: pongpong-bot
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DISCORD_SERVER_ID
        value: "1476750011076186154"
      - key: AUTHORIZED_USER_ID
        value: "791281791087935519"
      - key: PONG_ROLE_NAME
        value: "PONG"

  - type: web
    name: pongpong-website
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start:website
